const DATA = [
	{
		id: 1,
		name: 'computer 420g',
		brand: 'hp',
		category: 'technology',
		combo: true,
		description: 'portable pc hd',
		price: 4000000,
		img: 'https://images.pexels.com/photos/2047905/pexels-photo-2047905.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
	},
	{
		id: 2,
		name: 'computer partable',
		brand: 'toshiba',
		category: 'technology',
		combo: true,
		description: 'portable pc hd ultra-K',
		price: 2500000,
		img: 'https://images.pexels.com/photos/5496464/pexels-photo-5496464.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=11',
	},
	{
		id: 3,
		name: 'camaro 67100',
		brand: 'chevrolet',
		category: 'transportation',
		combo: false,
		description: 'contable and fast',
		price: 60000000,
		img: 'https://images.pexels.com/photos/1545743/pexels-photo-1545743.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
	},
	{
		id: 4,
		name: 'volvo fast 1200',
		brand: 'volvo',
		category: 'transportation',
		combo: false,
		description: 'volvo-mobile',
		price: 40000000,
		img: 'https://images.pexels.com/photos/845405/pexels-photo-845405.jpeg',
	},
	{
		id: 5,
		name: 'samsung A20',
		brand: 'samsung',
		category: 'technology',
		combo: true,
		description: 'smartphone android',
		price: 1500000,
		img: 'https://images.pexels.com/photos/4171648/pexels-photo-4171648.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
	},
	{
		id: 6,
		name: 'shirt pants set',
		brand: 'falabella',
		category: 'moda',
		combo: true,
		description: 'cool shirt pants set',
		price: 90000,
		img: 'https://images.pexels.com/photos/4090831/pexels-photo-4090831.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
	},
	{
		id: 7,
		name: 'leather hat',
		brand: 'falabella',
		category: 'moda',
		combo: true,
		description: 'cool leather hat',
		price: 100000,
		img: 'https://images.pexels.com/photos/4090637/pexels-photo-4090637.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
	},
	{
		id: 8,
		name: 'leather hat collection',
		brand: 'falabella',
		category: 'moda',
		combo: true,
		description: 'cool collection leather hat',
		price: 500000,
		img: 'https://images.pexels.com/photos/5698917/pexels-photo-5698917.jpeg?cs=srgb&dl=pexels-rodnae-productions-5698917.jpg&fm=jpg',
	},
	{
		id: 9,
		name: 'smarphone + airpods',
		brand: 'samsung',
		category: 'technology',
		combo: true,
		description: 'super smarphone + airpods pro 2000',
		price: 1800000,
		img: 'https://images.pexels.com/photos/5081399/pexels-photo-5081399.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
	},
	{
		id: 10,
		name: 'yamaha xtz',
		brand: 'yamaha',
		category: 'transportation',
		combo: true,
		description: 'super motorcycle',
		price: 8000000,
		img: 'https://images.pexels.com/photos/1430931/pexels-photo-1430931.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
	},
];

const DATA2 = [
	{
		nombre: 'Samsung Glaxy s20 FE',
		descripcion: 'Octa-core',
		Marca: 'Samsung',
		Categoria: 'celular',
		valor: 2620950,
		combo: 1,
		URL: 'https://i.imgur.com/mGuKxbi.jpeg',
	},
	{
		nombre: 'Xiaomi Redmi Note 10s',
		descripcion: 'Mediatek helio G95',
		Marca: 'Xiaomi',
		Categoria: 'Celular',
		valor: 1499900,
		combo: 0,
		URL: 'https://i.imgur.com/bBwwtPX.jpeg',
	},
	{
		nombre: 'Nokia G10 64G 4G',
		descripcion: 'Touchscreen',
		Marca: 'Nokia',
		Categoria: 'Celular',
		valor: 740900,
		combo: 0,
		URL: 'https://i.imgur.com/42ufS4I.jpeg',
	},
	{
		nombre: 'Oppo A54 128GB 4G',
		descripcion: 'Helio P35',
		Marca: 'Oppo',
		Categoria: 'Celular',
		valor: 1119900,
		combo: 0,
		URL: 'https://i.imgur.com/KvEwa5k.jpeg',
	},
	{
		nombre: 'Samsung Galaxy A12 128GB 4G Dual Sim',
		descripcion: 'Batería: 5.000 mAh',
		Marca: 'Samsung',
		Categoria: 'Celular',
		valor: 726900,
		combo: 0,
		URL: 'https://i.imgur.com/xoLwUmN.jpeg',
	},
	{
		nombre: 'Oppo Reno 6 Lite 4G',
		descripcion: '4x 2 GHz + 4x 1.8 GHz',
		Marca: 'Oppo',
		Categoria: 'Celular',
		valor: 1824900,
		combo: 1,
		URL: 'https://i.imgur.com/ksaOj5r.jpeg',
	},
	{
		nombre: 'Realme C15 128GB 4G',
		descripcion: 'Qualcomm SM4250 Snapdragon 460',
		Marca: 'Realme',
		Categoria: 'Celular',
		valor: 696900,
		combo: 1,
		URL: 'https://i.imgur.com/sbFajVs.jpeg',
	},
	{
		nombre: 'Alcatel TCL 20E 128GB 4G',
		descripcion: 'Android 11',
		Marca: 'Alcatel',
		Categoria: 'Celular',
		valor: 569900,
		combo: 1,
		URL: 'https://imgur.com/yIvL14P',
	},
	{
		nombre: 'Xiaomi 11T 5G',
		descripcion: 'MTK D1200- Ultra 6nm 3.0 GHz',
		Marca: 'Xiaomi',
		Categoria: 'Celular',
		valor: 2411900,
		combo: 0,
		URL: 'https://i.imgur.com/yIvL14P.jpeg',
	},
	{
		nombre: 'iPhone 13 Pro',
		descripcion: 'iOS 15',
		Marca: 'Iphone',
		Categoria: 'Celular',
		valor: 8651960,
		combo: 1,
		URL: 'https://i.imgur.com/05XOmfd.jpeg',
	},
	{
		nombre: 'Portátil Acer A515-54-31s4 Core i3',
		descripcion: 'Intel Core i3 10110U',
		Marca: 'Acer',
		Categoria: 'Computador',
		valor: 2670900,
		combo: 1,
		URL: 'https://i.imgur.com/6n1lGWv.jpeg',
	},
	{
		nombre: 'Portátil HP 240 G8 Celeron',
		descripcion: 'Intel Celeron N4020',
		Marca: 'HP',
		Categoria: 'Computador',
		valor: 1762900,
		combo: 0,
		URL: 'https://i.imgur.com/rHUyLGb.jpeg',
	},
	{
		nombre: 'Portátil Lenovo IDEAPAD3 CI3',
		descripcion: 'Intel Core™ i3-10110U',
		Marca: 'Lenovo',
		Categoria: 'Computador',
		valor: 2901900,
		combo: 1,
		URL: 'https://i.imgur.com/vbcfx2O.jpeg',
	},
	{
		nombre: 'Portátil HP 15-ef2502la',
		descripcion: 'AMD Ryzen',
		Marca: 'HP',
		Categoria: 'Computador',
		valor: 387900,
		combo: 1,
		URL: 'https://i.imgur.com/LatUumw.jpeg',
	},
	{
		nombre: 'Portátil Dynabook Toshiba Tecra C50-E',
		descripcion: 'Intel Celeron Dual Core',
		Marca: 'Toshiba',
		Categoria: 'Computador',
		valor: 1849900,
		combo: 1,
		URL: 'https://i.imgur.com/M3dNLua.jpeg',
	},
	{
		nombre: 'Portátil ASUS E410MA Intel Celeron N4020 P Obsequio Morral',
		descripcion: 'Intel Celeron N4000',
		Marca: 'Asus',
		Categoria: 'Accesorio',
		valor: 1075900,
		combo: 1,
		URL: 'https://i.imgur.com/AA8qS9p.jpeg',
	},
	{
		nombre: 'Portatil Asus X543MA-DM1336 Intel',
		descripcion: 'Intel ® Celeron® N4020',
		Marca: 'Asus',
		Categoria: 'Computador',
		valor: 131099,
		combo: 1,
		URL: 'https://i.imgur.com/Dtihp7K.jpeg',
	},
	{
		nombre: 'Portatil Asus ChromeBook C204MA-GJ0470',
		descripcion: 'Memoria: 4GB',
		Marca: 'Asus',
		Categoria: 'Computador',
		valor: 979900,
		combo: 0,
		URL: 'https://i.imgur.com/NvgxE0E.png',
	},
	{
		nombre: 'HP AIO 22-df006la CORE i3-10110U',
		descripcion: 'Tienda: SmartBuy',
		Marca: 'HP',
		Categoria: 'Computador',
		valor: 1921598,
		combo: 1,
		URL: 'https://i.imgur.com/NM1xQcY.jpeg',
	},
	{
		nombre: 'Portatil Entry Ci7C',
		descripcion: 'Resolución: 1920x1080 HD',
		Marca: 'Entry',
		Categoria: 'Computador',
		valor: 2973000,
		combo: 1,
		URL: 'https://i.imgur.com/T5Tuu1e.png',
	},
	{
		nombre: 'Auriculares Xiaomi FlipBuds Pro',
		descripcion: 'Potencia: Puerto de carga: Tipo-C',
		Marca: 'Xiaomi',
		Categoria: 'Accesorio',
		valor: 799900,
		combo: 1,
		URL: 'https://i.imgur.com/LwXqTUC.jpeg',
	},
	{
		nombre: 'Huawei FreeBuds 4i',
		descripcion: 'Bluetooth: si',
		Marca: 'Huawei',
		Categoria: 'Accesorio',
		valor: 249900,
		combo: 1,
		URL: 'https://i.imgur.com/EDxB2I0.jpeg',
	},
	{
		nombre: 'Audífonos Nokia Clarity Earbuds Pro',
		descripcion: 'Clarity',
		Marca: 'Nokia',
		Categoria: 'Accesorio',
		valor: 429900,
		combo: 1,
		URL: 'https://i.imgur.com/vgyQpiu.jpeg',
	},
	{
		nombre: 'Audifono Sennheiser CX 120BT',
		descripcion: 'Garantía: 2 años',
		Marca: 'Sennheiser',
		Categoria: 'Accesorio',
		valor: 109900,
		combo: 1,
		URL: 'https://i.imgur.com/R11SyVE.jpeg',
	},
	{
		nombre: 'Teclado y Mouse Inalámbrico ARG KB 7436',
		descripcion: 'ARG KB 7436',
		Marca: 'HP',
		Categoria: 'Accesorio',
		valor: 72900,
		combo: 1,
		URL: 'https://i.imgur.com/q0AmRRH.jpeg',
	},
	{
		nombre: 'Base Refrigerante Jaltech Mobile 3-H1',
		descripcion: 'Garantía: 6 Meses',
		Marca: 'Jaltech',
		Categoria: 'Accesorio',
		valor: 61900,
		combo: 1,
		URL: 'https://i.imgur.com/yCcqdp6.jpeg',
	},
	{
		nombre: 'Mi Portable Electric Air Compressor Xiaomi',
		descripcion: 'Tiempo de carga: menos de 3 horas',
		Marca: 'Xiaomi',
		Categoria: 'Accesorio',
		valor: 243900,
		combo: 0,
		URL: 'https://i.imgur.com/x7LSjPU.jpeg',
	},
	{
		nombre: 'Hub Belkin USB-C con 4 Puertos SUB-C Belkin',
		descripcion: 'Compatibilidad: 2 puertos USB-C / 2 puertos USB-A / Cargue periféricos con 900mAh(compartido).',
		Marca: 'Belkin',
		Categoria: 'Accesorio',
		valor: 230900,
		combo: 1,
		URL: 'https://i.imgur.com/mYynK6h.jpeg',
	},
	{
		nombre: 'Soporte Belkin de Carga Inalámbrica + Altavoz BOOST-CHARGE™',
		descripcion: 'Peso: 110 g.',
		Marca: 'Belkin',
		Categoria: 'Accesorio',
		valor: 260900,
		combo: 1,
		URL: 'https://i.imgur.com/jlJO7S7.jpeg',
	},
	{
		nombre: 'Mouse Vertical Inalambrico Jaltech 801',
		descripcion: 'Tienda: Tecnigo',
		Marca: 'Jaltech',
		Categoria: 'Accesorio',
		valor: 55900,
		combo: 0,
		URL: 'https://i.imgur.com/C1O3yMx.jpeg',
	},
];

const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
const getAllData = async () => {
	const res = await fetch('http://test.movilbox.co:888/test_mbox/test.php?metodo=productos');
	const data = await res.json();

	const dt = data.map((e, idx) => ({
		id: idx + 1,
		name: e.nombre,
		brand: e.Marca,
		category: e.Categoria.toLowerCase(),
		combo: e.combo === 1 ? true : false,
		description: e.descripcion,
		price: e.valor,
		img: e.URL,
	}));
	await delay(200);
	return dt;
};

export default getAllData;
