import { INITIAL_CALL_DATA } from './dataDucks';
import { INITIAL_CALL_FILTERS, SELECT_FILTER, FILTER_PRODUCTS, SET_FILTERED_PRODUCTS_BY_SEARCHBAR, RESET_FILTERS } from './filtersDucks';
import { ADD_TO_COMBOS } from './combosDucks';
import { SET_KEYWORD } from './keywordDucks';
import { ADD_TO_TOTAL, SUBSTRACT_TO_TOTAL } from './totalDucks';
import { ADD_TO_CART, REMOVE_TO_CART } from './cartDucks';

export {
	INITIAL_CALL_DATA,
	INITIAL_CALL_FILTERS,
	SELECT_FILTER,
	FILTER_PRODUCTS,
	SET_FILTERED_PRODUCTS_BY_SEARCHBAR,
	RESET_FILTERS,
	ADD_TO_COMBOS,
	SET_KEYWORD,
	ADD_TO_TOTAL,
	SUBSTRACT_TO_TOTAL,
	ADD_TO_CART,
	REMOVE_TO_CART,
};
